
package sk.kopr.ajs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AJSPort", targetNamespace = "http://localhost:8080/ajs?wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AJSPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns sk.kopr.ajs.AddSubjectResponse
     * @throws SubjectExist_Exception
     */
    @WebMethod(action = "http://localhost:8080/ajs?wsdl/addSubject")
    @WebResult(name = "AddSubjectResponse", targetNamespace = "urn:X-kopr", partName = "parameters")
    public AddSubjectResponse addSubject(
        @WebParam(name = "AddSubjectRequest", targetNamespace = "urn:X-kopr", partName = "parameters")
        AddSubjectRequest parameters)
        throws SubjectExist_Exception
    ;

}
