
package sk.kopr.ajs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AJSService", targetNamespace = "http://localhost:8080/ajs?wsdl", wsdlLocation = "file:/C:/Users/aha/SOAP/kopr-ajs/src/ajs.wsdl")
public class AJSService
    extends Service
{

    private final static URL AJSSERVICE_WSDL_LOCATION;
    private final static WebServiceException AJSSERVICE_EXCEPTION;
    private final static QName AJSSERVICE_QNAME = new QName("http://localhost:8080/ajs?wsdl", "AJSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/aha/SOAP/kopr-ajs/src/ajs.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AJSSERVICE_WSDL_LOCATION = url;
        AJSSERVICE_EXCEPTION = e;
    }

    public AJSService() {
        super(__getWsdlLocation(), AJSSERVICE_QNAME);
    }

    public AJSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AJSSERVICE_QNAME, features);
    }

    public AJSService(URL wsdlLocation) {
        super(wsdlLocation, AJSSERVICE_QNAME);
    }

    public AJSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AJSSERVICE_QNAME, features);
    }

    public AJSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AJSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AJSPort
     */
    @WebEndpoint(name = "AJSPort")
    public AJSPort getAJSPort() {
        return super.getPort(new QName("http://localhost:8080/ajs?wsdl", "AJSPort"), AJSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AJSPort
     */
    @WebEndpoint(name = "AJSPort")
    public AJSPort getAJSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080/ajs?wsdl", "AJSPort"), AJSPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AJSSERVICE_EXCEPTION!= null) {
            throw AJSSERVICE_EXCEPTION;
        }
        return AJSSERVICE_WSDL_LOCATION;
    }

}
